apiVersion: apps/v1
kind: Deployment
metadata:
  name: filterpage-deployment
  labels:
    app: filterpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filterpage
  template:
    metadata:
      labels:
        app: filterpage
    spec:
      containers:
      - name: filterpage
        image: zeenpc/filterpage:v1
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: filterpage-service
spec:
  selector:
    app: filterpage
  ports:
    - port: 5000
