apiVersion: apps/v1
kind: Deployment
metadata:
  name: filterpage-deployment
  labels:
    app: filterpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filterpage
  template:
    metadata:
      labels:
        app: filterpage
    spec:
      containers:
        - name: scraper
          image: mr0022/filterpage:latest
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: filterpage-service
spec:
  selector:
    app: filterpage
  ports:
    - port: 5000
